import type { RelationshipFlag } from "~/types/flag";

export const greenFlags = ref<Array<RelationshipFlag>>([
  {
    id: "G01",
    name: "Otwarta rozmowa o problemach",
    category: "communication",
    weight: 3,
    active: false,
  },
  {
    id: "G02",
    name: "Potrafi powiedzieć, czego potrzebuje",
    category: "communication",
    weight: 2,
    active: false,
  },
  {
    id: "G03",
    name: "Nie unika trudnych rozmów",
    category: "communication",
    weight: 2,
    active: false,
  },
  {
    id: "G04",
    name: "Potrafi spokojnie rozwiązywać konflikty",
    category: "communication",
    weight: 3,
    active: false,
  },

  {
    id: "G05",
    name: "Jest szczera nawet w niewygodnych sytuacjach",
    category: "trust",
    weight: 3,
    active: false,
  },
  {
    id: "G06",
    name: "Przyznaje się do błędów",
    category: "trust",
    weight: 2,
    active: false,
  },
  {
    id: "G07",
    name: "Jej zachowanie jest spójne ze słowami",
    category: "trust",
    weight: 3,
    active: false,
  },
  {
    id: "G08",
    name: "Nie manipuluje informacjami dotyczącymi innych mężczyzn",
    category: "trust",
    weight: 2,
    active: false,
  },

  {
    id: "G09",
    name: "Respektuje ustalone granice związku",
    category: "boundaries",
    weight: 4,
    active: false,
  },
  {
    id: "G10",
    name: "Sama jasno komunikuje granice innym osobom",
    category: "boundaries",
    weight: 3,
    active: false,
  },
  {
    id: "G11",
    name: "Nie ukrywa kontaktów z innymi mężczyznami",
    category: "boundaries",
    weight: 2,
    active: false,
  },
  {
    id: "G12",
    name: "Reaguje, gdy ktoś przekracza jej granice",
    category: "boundaries",
    weight: 3,
    active: false,
  },

  {
    id: "G13",
    name: "Jest zaangażowana w relację",
    category: "relationship",
    weight: 3,
    active: false,
  },
  {
    id: "G14",
    name: "Inicjuje wspólne spędzanie czasu",
    category: "relationship",
    weight: 2,
    active: false,
  },
  {
    id: "G15",
    name: "Wspólnie planuje przyszłość",
    category: "relationship",
    weight: 2,
    active: false,
  },
  {
    id: "G16",
    name: "Okazuje partnerowi zainteresowanie",
    category: "relationship",
    weight: 2,
    active: false,
  },

  {
    id: "G17",
    name: "Nie potrzebuje ciągłego zewnętrznego potwierdzania swojej atrakcyjności",
    category: "social",
    weight: 2,
    active: false,
  },
  {
    id: "G18",
    name: "Potrafi odrzucić flirt innych osób",
    category: "social",
    weight: 3,
    active: false,
  },
  {
    id: "G19",
    name: "Nie wykorzystuje zazdrości jako mechanizmu obronnego",
    category: "social",
    weight: 2,
    active: false,
  },
  {
    id: "G20",
    name: "Szanuje partnera również przy znajomych",
    category: "social",
    weight: 2,
    active: false,
  },

  {
    id: "G21",
    name: "Bierze odpowiedzialność za swoje decyzje",
    category: "accountability",
    weight: 3,
    active: false,
  },
  {
    id: "G22",
    name: "Potrafi przeprosić",
    category: "accountability",
    weight: 2,
    active: false,
  },
  {
    id: "G23",
    name: "Wyciąga wnioski z własnych błędów",
    category: "accountability",
    weight: 3,
    active: false,
  },
  {
    id: "G24",
    name: "Stara się naprawiać problemy zamiast je ukrywać",
    category: "accountability",
    weight: 3,
    active: false,
  },
]);

export const redFlags = ref<Array<RelationshipFlag>>([
  {
    id: "R01",
    name: "Notorycznie unika rozmów o problemach",
    category: "communication",
    weight: -3,
    critical: false,
    active: false,
  },
  {
    id: "R02",
    name: "Odwraca winę na partnera",
    category: "communication",
    weight: -3,
    critical: false,
    active: false,
  },
  {
    id: "R03",
    name: "Manipuluje podczas konfliktów",
    category: "communication",
    weight: -4,
    critical: false,
    active: false,
  },
  {
    id: "R04",
    name: "Celowo ukrywa istotne informacje na temat innych mężczyzn",
    category: "communication",
    weight: -5,
    critical: false,
    active: false,
  },

  {
    id: "R05",
    name: "Często kłamie na temat innych mężczyzn",
    category: "trust",
    weight: -5,
    critical: false,
    active: false,
  },
  {
    id: "R06",
    name: "Przyłapano ją na wielokrotnym kłamstwie",
    category: "trust",
    weight: -6,
    critical: true,
    active: false,
  },
  {
    id: "R07",
    name: "Jej wersje wydarzeń często się zmieniają",
    category: "trust",
    weight: -4,
    critical: false,
    active: false,
  },
  {
    id: "R08",
    name: "Ukrywa kontakty, które mogą mieć romantyczny lub seksualny charakter",
    category: "trust",
    weight: -6,
    critical: true,
    active: false,
  },

  {
    id: "R09",
    name: "Notorycznie flirtuje z innymi mężczyznami",
    category: "boundaries",
    weight: -6,
    critical: true,
    active: false,
  },
  {
    id: "R10",
    name: "Celowo utrzymuje alternatywne opcje romantyczne",
    category: "boundaries",
    weight: -7,
    critical: true,
    active: false,
  },
  {
    id: "R11",
    name: "Przekracza granice związku i bagatelizuje partnera",
    category: "boundaries",
    weight: -7,
    critical: true,
    active: false,
  },
  {
    id: "R12",
    name: "Ukrywa relację lub kontakt przed partnerem",
    category: "boundaries",
    weight: -7,
    critical: true,
    active: false,
  },

  {
    id: "R13",
    name: "Wyraźnie traci zainteresowanie relacją i odmawia rozmowy o tym",
    category: "relationship",
    weight: -3,
    critical: false,
    active: false,
  },
  {
    id: "R14",
    name: "Regularnie szuka romantycznej uwagi poza związkiem",
    category: "relationship",
    weight: -6,
    critical: false,
    active: false,
  },
  {
    id: "R15",
    name: "Porównuje partnera z innymi w sposób podważający relację",
    category: "relationship",
    weight: -3,
    critical: false,
    active: false,
  },
  {
    id: "R16",
    name: "Celowo wzbudza lub okazuje zazdrość",
    category: "relationship",
    weight: -4,
    critical: false,
    active: false,
  },

  {
    id: "R17",
    name: "Regularnie prowadzi romantycznie lub seksualnie nacechowane rozmowy z innymi mężczyznami",
    category: "social",
    weight: -7,
    critical: true,
    active: false,
  },
  {
    id: "R18",
    name: "Ukrywa spotkania z mężczyznami, które mogą być zainteresowane romantycznie",
    category: "social",
    weight: -7,
    critical: true,
    active: false,
  },
  {
    id: "R19",
    name: "Utrzymuje ukrywany kontakt z byłym partnerem",
    category: "social",
    weight: -5,
    critical: false,
    active: false,
  },
  {
    id: "R20",
    name: "Akceptuje zachowania wobec siebie, które sama uznałaby za zdradę u partnera",
    category: "social",
    weight: -4,
    critical: true,
    active: false,
  },

  {
    id: "R21",
    name: "Nigdy nie bierze odpowiedzialności za swoje błędy",
    category: "accountability",
    weight: -4,
    critical: false,
    active: false,
  },
  {
    id: "R22",
    name: "Posiada więcej kolegów niż koleżanek",
    category: "accountability",
    weight: -5,
    critical: false,
    active: false,
  },
  {
    id: "R23",
    name: "Powtarza te same zachowania mimo wcześniejszych konsekwencji",
    category: "accountability",
    weight: -5,
    critical: false,
    active: false,
  },
  {
    id: "R24",
    name: "Uważa, że zasady związku jej nie dotyczą",
    category: "accountability",
    weight: -7,
    critical: true,
    active: false,
  },
]);
